### ISSUE TITLE
fixing the batch parser...

### ISSUE THREAD

**Issue by pickettj** [pickettj/xml_development_eurasia#3]
@iamlemec 

I'm modifying the [custom Markdown > XML parser](https://github.com/pickettj/xml_development_eurasia/tree/master/markdown_parser) you helped me design, but am having some issues:

(1) There's something about my [parse_md](https://github.com/pickettj/xml_development_eurasia/blob/master/markdown_parser/parser_functions.py) function it doesn't like. I'm trying to get it to work for both .md and .txt file types, but for some reason the loop returns a `AttributeError: 'NoneType' object has no attribute 'groups'` when it gets to the .md files.

(2) For me, the jupyter notebook was not reading my serial_no function on import. Is some of my syntax wrong?

(3) I'm sure some of my file transfer syntax is not quite right and / or the wrong way to do it...

For context, here's the contents of the input folder:

```
['archive_docs_now_at_xml_stage_do_not_use',
 'document_conversion_backlog',
 'parser_output.xml',
 'ser560.txt',
 'ser560.xml',
 'ser72.md',
 'ser808.md',
 'ser809.md',
 'ser811.md',
 'ser812.md',
 'ser813.md',
 'ser814.md',
 'ser815.md',
 'ser816.md',
 'ser817.md',
 'ser818.md',
 'ser842.md',
 'ser843.md',
 'ser857.md',
 'ser876.md',
 'ser877.md']

**Comment by iamlemec** [comment]
(1) Somehow it must be that the regex is not matching (in which case it returns None). It seems like it should match though.

(2) Do you have autoreload on? It seems like it might be failing to do that because of a syntax error. The fact that the error messages are offset so they're showing errors on comment lines makes me think this might be it. Try reloading the notebook (press 00). This could also relate to (1).

(3) Is this when you're moving the files to the archive path? You can just give the final path directly to the open function when you write it.

**Comment by pickettj** [comment]
Thanks, @iamlemec! Some (not all) of the issues were indeed solved by reloading.

I still can't figure out why calling this function (with `pf.serial_no("ser_92")`):

```python
def serial_no (input_file):
    # Isolating the document serial number from the file name
    if ".txt" in input_file:
        ret = re.match(r'[^0-9]*([0-9]+)\.txt', input_file)
        doc_ser, = ret.groups()
    elif ".md" in input_file:
        ret = re.match(r'[^0-9]*([0-9]+)\.md', input_file)
        doc_ser, = ret.groups()
    return  doc_ser
```
results in a "local variable 'doc_ser' referenced before assignment" error in the Jupyter notebook.

**Comment by pickettj** [comment]
Got it working: thanks @iamlemec !
